version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Utilisation de l'étape "development"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm test
    volumes:
      - .:/app
      - /app/node_modules

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production  # Utilisation de l'étape "production"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped  # Redémarrage automatique en cas de crash
