version: 2.1

orbs:
  node: circleci/node@5
  docker: circleci/docker@2

executors:
  node-executor:
    docker:
      - image: node:18-bullseye
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            set -e
            npm install
      - run:
          name: "Linting code"
          command: npm run lint
      - run:
          name: "Build project"
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - .next
            - public

  test:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: "Run tests"
          command: |
            set -e
            npm run test

  docker-build:
    docker:
      - image: docker:20.10.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.16
      - run:
          name: "Build and tag Docker image"
          command: |
            set -e
            docker build -t monrepo/monapp:latest .
      - run:
          name: "Login to Docker Hub"
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: "Push Docker image"
          command: |
            set -e
            docker tag monrepo/monapp:latest monrepo/monapp:$CIRCLE_SHA1
            docker push monrepo/monapp:$CIRCLE_SHA1
            docker push monrepo/monapp:latest

  deploy_vercel_dev:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Deploy to Vercel (Development)"
          command: |
            set -e
            vercel --token $VERCEL_TOKEN --prod

  deploy_vercel_int:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Deploy to Vercel (Integration)"
          command: |
            set -e
            vercel --token $VERCEL_TOKEN --prod --scope mon-organisation-integration

  deploy_vercel_prod:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Deploy to Vercel (Production)"
          command: |
            set -e
            vercel --token $VERCEL_TOKEN --prod --scope mon-organisation

workflows:
  version: 2

  feature-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
    filters:
      branches:
        only:
          - /^feature\/.*/

  develop-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - test
      - deploy_vercel_dev:
          requires:
            - docker-build
    filters:
      branches:
        only:
          - develop

  integration-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - test
      - deploy_vercel_int:
          requires:
            - docker-build
    filters:
      branches:
        only:
          - integration

  production-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - test
      - deploy_vercel_prod:
          requires:
            - docker-build
    filters:
      branches:
        only:
          - main
