version: 2.1

orbs:
  node: circleci/node@5
  docker: circleci/docker@2

executors:
  node-executor:
    docker:
      - image: circleci/node:18
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: npm install
      - run:
          name: "Linting"
          command: npm run lint
      - run:
          name: "Build project"
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - .next
            - public

  test:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: "Run tests"
          command: npm run test

  docker-build:
    docker:
      - image: docker:20.10.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.16
      - run:
          name: "Build and tag Docker image"
          command: |
            docker build -t monrepo/monapp:latest .
      - run:
          name: "Push Docker image to Docker Hub"
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag monrepo/monapp:latest monrepo/monapp:$CIRCLE_SHA1
            docker push monrepo/monapp:$CIRCLE_SHA1
            docker push monrepo/monapp:latest

  deploy_vercel_dev:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Deploy to Vercel (Development)"
          command: |
            vercel --token $VERCEL_TOKEN --prod

  deploy_vercel_prod:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Deploy to Vercel (Production)"
          command: |
            vercel --token $VERCEL_TOKEN --prod --scope mon-organisation

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - build
      - deploy_vercel_dev:
          requires:
            - test
            - docker-build
          filters:
            branches:
              only: develop
      - deploy_vercel_prod:
          requires:
            - test
            - docker-build
          filters:
            branches:
              only: main
